fix: introduce new DesktopFile class
linuxdeepin/dde-application-manager pull request #10
Opened 2023-03-07 02:57 UTC by black-desk

KeyFile::saveToFile not guaranteed section order, which is not the right
behavior of desktop file. XDG requires the first section of desktop file
always to be "Desktop Entry".

So I write a new DesktopFile class, which override the saveToFile method
of KeyFile, to make it work.

2023-03-07 06:53 UTC, black-desk commented
[dde-application-manager_1.0.8_amd64.zip](https://github.com/linuxdeepin/dde-application-manager/files/10906278/dde-application-manager_1.0.8_amd64.zip)

2023-03-07 06:55 UTC, black-desk commented
The old exec parsing behavior is completely wrong, I rewrite them.

2023-03-14 08:20 UTC, BLumia reviewed
dtkcore 本身应该就带了一个 DDesktopEntry，那个不能满足要求的吗

2023-03-14 08:48 UTC, black-desk commented
> dtkcore 本身应该就带了一个 DDesktopEntry，那个不能满足要求的吗

没看过 不过这里并不是entry的问题

是那个entry取出来以后要怎么解析成要跑的命令的问题

2023-03-14 12:39 UTC, black-desk commented
> > dtkcore 本身应该就带了一个 DDesktopEntry，那个不能满足要求的吗
> 
> 没看过 不过这里并不是entry的问题
> 
> 是那个entry取出来以后要怎么解析成要跑的命令的问题

可以考虑把整个这个类都换成dtk里的entry 但是这个项目是不是计划中要重做来着

2023-03-14 15:01 UTC, BLumia commented
> 但是这个项目是不是计划中要重做来着

发首个正式版之前来得及大修吗（x

2023-03-14 15:30 UTC, black-desk commented
> > 但是这个项目是不是计划中要重做来着
> 
> 发首个正式版之前来得及大修吗（x
> 
> 感觉如果真能按之前的讨论做大幅度调整的话，大概是 side by side 做两个不同的共存，然后逐步砍掉目前的实现吧。

但是正式版发了接口是不是就不能动了(x

2023-03-30 03:24 UTC, black-desk commented
@BLumia @zccrs beta发布的时候还修不修这些am启动应用的问题 如果这些东西在考虑范围内的话am的改动还挺多的.

2023-03-30 03:34 UTC, zccrs commented
> > > 但是这个项目是不是计划中要重做来着
> > 
> > 
> > 发首个正式版之前来得及大修吗（x
> > 感觉如果真能按之前的讨论做大幅度调整的话，大概是 side by side 做两个不同的共存，然后逐步砍掉目前的实现吧。
> 
> 但是正式版发了接口是不是就不能动了(x

在社区版上可以动，把这个项目标记为技术预览版本，不作为正式版推出。

2023-03-30 03:35 UTC, zccrs commented
> 

看具体的问题影响大小和需要改动的范围以及修复难度

2023-03-30 03:36 UTC, zccrs commented
> > 
> 
> 看具体的问题影响大小和需要改动的范围以及修复难度

我的建议是先用比较小的改动解决一部分严重的问题。现阶段就开始重写它，但是不在Beta中集成重新的版本，Release版本中集成。

2023-03-30 07:55 UTC, zccrs requested changes

2023-03-30 07:55 UTC, zccrs commented on src/lib/desktopfile.cpp
> +// SPDX-FileCopyrightText: 2018 - 2023 UnionTech Software Technology Co., Ltd.
时间错了？

2023-03-30 07:55 UTC, zccrs commented on src/lib/desktopfile.h
> +// SPDX-FileCopyrightText: 2018 - 2023 UnionTech Software Technology Co., Ltd.
同上

2023-03-30 07:55 UTC, zccrs commented on src/lib/keyfile.cpp
> +        if(!writeSectionToFile(im.first,im.second,sfp)){
代码格式

2023-03-30 07:56 UTC, black-desk commented on src/lib/desktopfile.cpp
> +// SPDX-FileCopyrightText: 2018 - 2023 UnionTech Software Technology Co., Ltd.
应该是啥

2023-03-30 09:52 UTC, zccrs commented on src/lib/desktopfile.cpp
> +// SPDX-FileCopyrightText: 2018 - 2023 UnionTech Software Technology Co., Ltd.
是新写的文件吗，是的话只写个 2023 即可

2023-03-31 01:36 UTC, zccrs approved these changes

2023-04-03 01:42 UTC, black-desk commented
/merge

2023-04-03 01:42 UTC, merged