fix: 任务栏最近使用任务区域残留锯齿图标应用
linuxdeepin/dde-application-manager pull request #11
Opened 2023-03-13 07:45 UTC by ArchieMeng

部分修复了两种场景：
- 无法点击图标打开的锯齿应用在系统启动时残留在最近任务栏（如Deepin-Lock）
- 锯齿图标应用被关闭后，残留在最近任务栏．（如dde-dconfig-editor）

当前存在问题：
第二种情况在锯齿应用被移除时，任务栏会闪一下．

Issue: https://github.com/linuxdeepin/developer-center/issues/3788
Log: 任务栏最近使用任务区域残留锯齿图标应用

2023-03-28 07:22 UTC, tsic404 commented
@BLumia dock 现在移除item没有动画，在recentApp区域移除无desktopfile的程序后，会很僵硬的闪烁一下 :cry:

2023-04-18 13:02 UTC, dengbo11 requested changes

2023-04-18 13:02 UTC, dengbo11 commented on src/modules/dock/dock.cpp
> +            if (desktopInfo.shouldShow())
这一部分与下面1254-1257重复,可以封装成一个函数, 以后有其他地方使用可直接调用函数,就不用去重复实现了

2023-04-22 04:01 UTC, BLumia approved these changes

2023-04-22 04:02 UTC, dengbo11 approved these changes

2023-04-22 04:02 UTC, merged