fix some issues
linuxdeepin/dde-application-manager pull request #165
Opened 2024-02-01 09:37 UTC by ComixHe

2024-02-01 09:56 UTC, wineee commented
/+1

2024-02-01 10:11 UTC, black-desk requested changes

2024-02-01 10:11 UTC, black-desk commented on src/dbus/applicationservice.h
> +    void appendScaleFactor(QVariantMap &optionsMap) const noexcept;
是不是不应该写在这个类里面?

2024-02-01 10:11 UTC, black-desk commented on apps/app-launch-helper/src/variantvalue.cpp
>  int StringValue::appendValue(std::string &&value) noexcept
函数名字改一下吧 你这个函数名+这个签名 完全看不出来value里面可以是一大串东西

2024-02-01 10:48 UTC, ComixHe commented on apps/app-launch-helper/src/variantvalue.cpp
>  int StringValue::appendValue(std::string &&value) noexcept
之前改的时候看错签名了，实际上`as`是用`ASValue::appendValue`填充参数，这个函数的实现不需要修改

2024-02-01 11:00 UTC, ComixHe commented on src/dbus/applicationservice.h
> +    void appendScaleFactor(QVariantMap &optionsMap) const noexcept;
抽成cpp文件里的不公开函数了

2024-02-02 06:49 UTC, black-desk approved these changes

2024-02-02 09:58 UTC, merged