feat: support to record launched details
linuxdeepin/dde-application-manager pull request #178
Opened 2024-03-20 09:32 UTC by 18202781743

Recording who launched it, and it's launched times.

2024-03-21 03:50 UTC, ComixHe approved these changes

2024-03-21 05:53 UTC, zccrs requested changes

2024-03-21 05:53 UTC, zccrs commented on src/dbus/applicationservice.cpp
> +        return true;
为什么不是返回false呢

2024-03-21 05:53 UTC, zccrs commented on src/dbus/applicationservice.cpp
> +bool ApplicationService::updateLaunchedDetails(const ObjectInterfaceMap &launchedDetails) noexcept
这里为什么不直接接受一个 QVariantMap 呢，在 ObjectInterfaceMap 和 QVariantMap 之间转来转去的也挺麻烦，内部数据的存储和操作可以统一为 QVariantMap，只在对外的 DBus 返回结果中转成 DBus 需要的数据类型

2024-03-21 05:53 UTC, zccrs commented on src/dbus/applicationservice.cpp
> +    QVariantMap &typeTimes = launchedDetails[::LaunchedType];
对于 LaunchedType的存储不用上 QVariantMap 这么复杂的数据，直接是一个 QVector<int> 就可以了，压根不需要做个map关系，Other AutoStart User 可以做成三个枚举值，只是对外的DBus接口是个map

2024-03-21 05:53 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +                          selected as `AutoStart`,`User`,`Other`. it's useful in
感觉保留AutoStart和User就够了，对于不是AutoStart和User的在内部代码中都表示为Other，在接口方面，只要没有明确指定为 AutoStart 和 User，就是 Other，没有必要专门搞一项让它明确指定为 Other

2024-03-21 05:55 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +                          selected as `AutoStart`,`User`,`Other`. it's useful in
保持这些属性名用小驼峰或者用下划线吧 冒出来一个大驼峰的不是很协调.

2024-03-21 09:39 UTC, 18202781743 commented on src/dbus/applicationservice.cpp
> +    QVariantMap &typeTimes = launchedDetails[::LaunchedType];
需要对不同类型的LaunchedType分别统计,

2024-03-21 09:40 UTC, 18202781743 commented on src/dbus/applicationservice.cpp
> +        return true;
这里不包含也表示正常,只有写错误才返回false,上报错误信息,

2024-03-21 09:42 UTC, 18202781743 commented on src/dbus/applicationservice.cpp
> +bool ApplicationService::updateLaunchedDetails(const ObjectInterfaceMap &launchedDetails) noexcept
如果只是统计次数的话,用map就行,这里便于以后统计其它信息,用的是ObjectInterfaceMap, 多套了一层,
这里也没有单独用变量存一个,直接写到storage里了,

2024-03-22 10:23 UTC, 18202781743 commented
https://github.com/linuxdeepin/dtkcore/pull/408

2024-03-25 11:31 UTC, ComixHe requested changes

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/CMakeLists.txt
> +    Qt${QT_VERSION_MAJOR}::DBus
这些都不需要，直接链接dde_am_static和dtk6core就行

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/CMakeLists.txt
> +target_compile_definitions(${BIN_NAME} PRIVATE
改成serviceID会不会好一点？AM并不属于APP

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/CMakeLists.txt
> +    FILES ${PROJECT_SOURCE_DIR}/misc/dsg/configs/dde-am/org.deepin.dde-am.json
.../dde-application-manager/org.desktopspec.ApplicationManager1.json

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +        return {};
这里返回DUnexpected，上报错误信息和错误码，类似于这样:

```cpp
return DUnexpected{emplace_tag::USE_EMPLACE, reply.error().type(), reply.error().message()};
```

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +namespace {
如果用匿名命名空间的话，下面的static函数就全放在匿名命名空间里吧

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +        qWarning() << "failed to fetch application infors" << reply.errorMessage();
infors -> infos

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +    Q_ASSERT(!arguments.isEmpty());
建议不要直接Q_ASSERT，用qFatal或者Q_ASSERT_X报一下原因

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/main.cpp
> +            std::cout << qPrintable(item) << std::endl;
用Qt就统一qDebug吧，下同

2024-03-25 11:31 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +bool Launcher::launch()
用DExpected把错误一路上报，就不需要m_errorMsg了

2024-03-25 11:51 UTC, 18202781743 commented on apps/dde-am/src/CMakeLists.txt
> +    Qt${QT_VERSION_MAJOR}::DBus
这个tool没有用到dde_am_static里的这么多符号啊,

2024-03-25 11:54 UTC, 18202781743 commented on apps/dde-am/src/CMakeLists.txt
> +target_compile_definitions(${BIN_NAME} PRIVATE
这里的所有二进制, 都将serviceID当作AppID?

2024-03-25 13:20 UTC, 18202781743 commented on apps/dde-am/src/CMakeLists.txt
> +    FILES ${PROJECT_SOURCE_DIR}/misc/dsg/configs/dde-am/org.deepin.dde-am.json
配置文件命名小写, 现在是准备把这一组服务的二进制都以dde-application-manager 为APPID么?

2024-03-26 01:51 UTC, ComixHe requested changes

2024-03-26 01:51 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +static DExpected<T> parseDBusField(const QVariantMap &map, const QString &key)
这里不需要static了，下同

2024-03-26 01:51 UTC, ComixHe commented on apps/dde-am/src/launcher.cpp
> +        return {};
漏了一个

2024-03-26 02:30 UTC, 18202781743 commented on apps/dde-am/src/launcher.cpp
> +        return {};
这里可以不用错误啊,

2024-03-26 02:48 UTC, ComixHe approved these changes

2024-03-26 03:25 UTC, zccrs requested changes

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/launcher.cpp
> +    static bool initialized = false;
可以直接用 QGlobalStatic 实现全局的懒加载对象

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/launcher.cpp
> +Dtk::Core::DExpected<void> Launcher::launch()
这里需要命名空间吗

2024-03-26 03:25 UTC, zccrs commented on CMakeLists.txt
> +set(APPLICATION_SERVICEID "org.deepin.applicationmanager1")
这是个啥id, DBus的吗，不叫这个吧

2024-03-26 03:25 UTC, zccrs commented on CMakeLists.txt
> +set(APPLICATION_SERVICEID "org.deepin.applicationmanager1")
如果是DConfig的，不用以1结尾，另外加个备注说明一下，此外，`applicationmanager`符合dconfig的命名规范吗？

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    QCommandLineParser parser;
怎么没有加任何参数呢？应该用个参数控制是不是要把本次启动的行为记录到启动次数中，比如 `--by-user`

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    if (pos1 == u8"list") {
用 QCommandLineOption

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    QMetaObject::invokeMethod(&app, [launcher = std::move(launcher)]() {
为什么要延迟调用，是因为DBus调用依赖Qt的事件循环吗？

2024-03-26 03:25 UTC, zccrs commented on misc/CMakeLists.txt
> +    FILES ${CMAKE_CURRENT_LIST_DIR}/dsg/configs/applicationmanager1/org.deepin.applicationmanager1.tools.json
直接叫 `org.deepin.dde.am` 不好了，跟二进制的名字对应

2024-03-26 03:25 UTC, zccrs commented on apps/dde-am/src/launcher.cpp
> +    static bool initialized = false;
这是个命令行工具，又不是持续运行，没必要缓存这个数据吧

2024-03-26 03:29 UTC, 18202781743 commented on apps/dde-am/src/main.cpp
> +    QMetaObject::invokeMethod(&app, [launcher = std::move(launcher)]() {
嗯,如果是异步的话就需要了,

2024-03-26 03:30 UTC, 18202781743 commented on apps/dde-am/src/main.cpp
> +    QCommandLineParser parser;
用这个工具启动的,应该都是用户起的吧,这样就不用再加启动参数了,

2024-03-26 03:31 UTC, 18202781743 commented on apps/dde-am/src/launcher.cpp
> +    static bool initialized = false;
如果后续再加解析的话,就需要对它缓存了,

2024-03-26 03:33 UTC, 18202781743 commented on CMakeLists.txt
> +set(APPLICATION_SERVICEID "org.deepin.applicationmanager1")
单词之间用`-` 连接?

2024-03-26 03:35 UTC, 18202781743 commented on misc/CMakeLists.txt
> +    FILES ${CMAKE_CURRENT_LIST_DIR}/dsg/configs/applicationmanager1/org.deepin.applicationmanager1.tools.json
那改成org.deepin.dde-am行不?

2024-03-26 03:42 UTC, 18202781743 commented on apps/dde-am/src/main.cpp
> +    if (pos1 == u8"list") {
option 和 ParseAsPositionalArguments应该只能二选一吧, 如果那样的话,每次启动还得输入个-a 这样的option ?

2024-03-26 03:46 UTC, zccrs commented on CMakeLists.txt
> +set(APPLICATION_SERVICEID "org.deepin.applicationmanager1")
规范我忘记有没有说了，对于这个项目的话，可以选择跟二进制的名字一样如果二进制是用连字符，这里可以保持

2024-03-26 03:46 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    QCommandLineParser parser;
不，这个工具是个通用的，只是提供了为用户启动时记录次数的能力而已，不要变成了是为了用户启动设计的专门的工具

2024-03-26 03:48 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    if (pos1 == u8"list") {
positionalArguments 是给启动程序用的呀，这里的 list 是个很明确的参数，而不是 positionalArguments。就算加了 --list 参数，也不需要加个 -a 的参数

2024-03-26 03:49 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    QMetaObject::invokeMethod(&app, [launcher = std::move(launcher)]() {
判断一下，这个工具应该不需要异步调用dbus，甚至下面的 app.exec 需不需要执行都是个问号

2024-03-26 03:50 UTC, zccrs commented on misc/CMakeLists.txt
> +    FILES ${CMAKE_CURRENT_LIST_DIR}/dsg/configs/applicationmanager1/org.deepin.applicationmanager1.tools.json
没有叫这样的，dde开头的二进制都是指桌面环境，桌面环境自身应该是个域，只有仅用作单词分割目的时，才会是`org.deepin.dde-am`，比如 `org.deepin.dde.control-center`

2024-03-26 06:02 UTC, 18202781743 commented on apps/dde-am/src/main.cpp
> +    QMetaObject::invokeMethod(&app, [launcher = std::move(launcher)]() {
之前DConfig::setValue没有阻塞,是异步的,https://github.com/linuxdeepin/dtkcore/pull/408 改成同步的了,

2024-03-26 06:03 UTC, 18202781743 commented on CMakeLists.txt
> +set(APPLICATION_SERVICEID "org.deepin.applicationmanager1")
改成org.deepin.dde.application-manager吧,

2024-03-26 06:27 UTC, zccrs requested changes

2024-03-26 06:27 UTC, zccrs commented on apps/dde-am/src/launcher.cpp
> +        return;
给一个warning？

2024-03-26 06:27 UTC, zccrs commented on apps/dde-am/src/main.cpp
> +    parser.addVersionOption();
使用 addPositionalArgument

2024-03-26 08:24 UTC, black-desk commented on apps/dde-am/src/main.cpp
> +    QCommandLineParser parser;
> 不，这个工具是个通用的，只是提供了为用户启动时记录次数的能力而已，不要变成了是为了用户启动设计的专门的工具

啊? 好像和之前说的不一样?

2024-03-27 01:51 UTC, zccrs approved these changes

2024-03-27 06:26 UTC, merged