fix: crashed when removing a invalid index (-1)
linuxdeepin/dde-application-manager pull request #187
Opened 2024-04-17 06:43 UTC by FeiWang1119

handle the exceptional case that location is -1

Issue: https://github.com/linuxdeepin/developer-center/issues/7964

2024-04-18 04:28 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +    if (location == -1 && execList.back().contains(codeStr)) {
不能这么改，下面进行url替换的地方会用到location，Launch传url进来还是会崩溃，如果要改的话需要把改整个流程

2024-05-06 07:43 UTC, FeiWang1119 commented on src/dbus/applicationservice.cpp
> +    if (location == -1 && execList.back().contains(codeStr)) {
done

2024-05-07 02:30 UTC, ComixHe requested changes

2024-05-07 02:30 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +    if (str.count('%') == 1) {
不要这样改，因为Exec里允许%%这种转义

2024-05-07 02:31 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +    if (str.count('%') == 1) {
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

2024-05-07 03:33 UTC, FeiWang1119 commented on src/dbus/applicationservice.cpp
> +    if (str.count('%') == 1) {
done

2024-05-07 07:27 UTC, ComixHe approved these changes

2024-05-07 07:33 UTC, merged