feat: support apps launched directly by systemd
linuxdeepin/dde-application-manager pull request #189
Opened 2024-04-22 09:31 UTC by asterwyx

Do not filter out those not launched by application manager. Assume unit name as the app id. When Identify, assume there is only one unique instance.

Log: support apps launched directly by systemd
Related-to: https://github.com/linuxdeepin/developer-center/issues/8088

2024-04-22 09:45 UTC, ComixHe requested changes

2024-04-22 09:45 UTC, ComixHe commented on src/global.h
> +                launcher = rest.takeFirst();
格式化一下

2024-04-22 09:59 UTC, black-desk commented on src/dbus/applicationmanager1service.cpp
> +        }
```suggestion
    const auto &instances = (*app)->instances();
    if (ret.InstanceId.isEmpty() && instances.size() == 1) {
        // Maybe a dbus systemd service.
        instancePath = instances.constFirst();
    } else {
        instancePath = (*app)->findInstance(ret.InstanceId);
    }

    if (auto path = instancePath.path(); path.isEmpty()) {
        sendErrorReply(QDBusError::Failed, "can't find instance:" % ret.InstanceId);
        return {};

```

2024-04-22 09:59 UTC, black-desk commented on src/dbus/applicationmanager1service.cpp
> +        }
你看一下这样行不行

2024-04-22 10:03 UTC, black-desk commented on src/global.h
> +        applicationId = unitName.sliced(0, lastDotIndex);
``` c++
       return {unescapeApplicationId(applicationId), std::move(launcher), std::move(instanceId)};
```

直接这里加一个return 下面就不需要else了

2024-04-22 10:04 UTC, black-desk commented on src/global.h
> +        applicationId = unitName.sliced(0, lastDotIndex);
整个函数可以改成这样
```cpp
    QString instanceId;
    QString launcher;
    QString applicationId;

    qDebug() << "process unit:" << unitName;

    decltype(auto) appPrefix = u8"app-";
    if (!unitName.startsWith(appPrefix)) {
        // If not started by application manager, just remove suffix and take name as app id.
        auto lastDotIndex = unitName.lastIndexOf('.');
        applicationId = unitName.sliced(0, lastDotIndex);
        return {unescapeApplicationId(applicationId), std::move(launcher), std::move(instanceId)};
    }

    auto unit = unitName.sliced(sizeof(appPrefix) - 1);

    if (unit.endsWith(".service")) {
        auto lastDotIndex = unit.lastIndexOf('.');
        auto app = unit.sliced(0, lastDotIndex);  // remove suffix

        if (app.contains('@')) {
            auto atIndex = app.indexOf('@');
            instanceId = app.sliced(atIndex + 1);
            app.remove(atIndex, instanceId.length() + 1);
        }
        auto rest = app.split('-', Qt::SkipEmptyParts);
        if (rest.size() == 2) {
            launcher = rest.takeFirst();
        }
        if (rest.size() == 1) {
            applicationId = rest.takeFirst();
        }
    } else if (unit.endsWith(".scope")) {
        auto lastDotIndex = unit.lastIndexOf('.');
        auto app = unit.sliced(0, lastDotIndex);

        auto components = app.split('-');
        instanceId = components.takeLast();
        applicationId = components.takeLast();
        if (!components.isEmpty()) {
            launcher = components.takeLast();
        }
    } else {
        qDebug() << "it's not service or scope:" << unit << "ignore";
        return {};
    }

    return {unescapeApplicationId(applicationId), std::move(launcher), std::move(instanceId)};

```

2024-04-23 02:11 UTC, ComixHe approved these changes

2024-04-23 05:53 UTC, ComixHe approved these changes

2024-04-23 06:27 UTC, merged