fix: use XResQueryClientIds to get pid of xwindow
linuxdeepin/dde-application-manager pull request #19
Opened 2023-04-03 07:58 UTC by black-desk

Code copy from https://gitlab.gnome.org/GNOME/metacity/-/merge_requests/13/diffs

The xprop `_NET_WM_PID` is set by the client side, even if the process
in running in some container. But when pid_ns is unshared, the processes
in side a container, will not be able to get the "right" pid of itself.

The "new" XResQueryClientIds added to XRes will fix this issue by
produce the pid in server side.

refs:

- https://gitlab.freedesktop.org/xorg/xserver/-/issues/1022#note_497597
- https://www.x.org/releases/X11R7.7/doc/resourceproto/resproto.txt

close linuxdeepin/developer-center#3802

2023-04-03 07:58 UTC, black-desk commented
还没测试

2023-04-17 09:57 UTC, zccrs requested changes

2023-04-17 09:57 UTC, zccrs commented on src/modules/dock/windowidentify.cpp
>  {
加一下注释

2023-04-17 09:57 UTC, zccrs commented on src/modules/dock/windowidentify.cpp
>  {
试试改成list

2023-04-17 10:07 UTC, zccrs approved these changes

2023-04-17 10:08 UTC, black-desk commented
/merge

2023-04-17 10:09 UTC, merged