feat: add safe_sendErrorReply
linuxdeepin/dde-application-manager pull request #210
Opened 2024-05-15 07:51 UTC by kegechen

crash when Not called from DBus (ApplicationService::setAutoStart)

2024-05-15 07:59 UTC, ComixHe approved these changes

2024-05-15 08:17 UTC, ComixHe requested changes

2024-05-15 08:17 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +    if (!startDir.exists() && !startDir.mkpath(startDir.path()))
建目录失败的话也sendReply吧

2024-05-16 01:29 UTC, zccrs requested changes

2024-05-16 01:29 UTC, zccrs commented on src/dbus/applicationmanager1service.cpp
> +        safe_sendErrorReply(QDBusError::Failed, "add application to ApplicationManager failed.");
为什么全是 `QDBusError::Failed`，不还有其他类型的报错吗

2024-05-16 01:34 UTC, kegechen commented on src/dbus/applicationmanager1service.cpp
> +        safe_sendErrorReply(QDBusError::Failed, "add application to ApplicationManager failed.");
这个不涉及到本次修改。其他地方除了 Failed 还有 InternalError

2024-05-16 01:50 UTC, ComixHe submitted a review, later dismissed

2024-05-17 01:52 UTC, ComixHe approved these changes

2024-05-22 08:12 UTC, zccrs approved these changes

2024-05-22 08:14 UTC, merged