feat: add app extra env config
linuxdeepin/dde-application-manager pull request #214
Opened 2024-05-22 03:37 UTC by kegechen

e.g.
to fix #8667 add config { "FoxitReader": "QT_QPA_PLATFORM=xcb"}

Issue: https://github.com/linuxdeepin/developer-center/issues/8667

2024-05-22 05:15 UTC, 18202781743 commented on misc/dsg/configs/dde-application-manager/org.deepin.dde.am.json
> +    "appsExtraEnvironments": {
这个配置项,使用subpath可能比较合适, 它使用的应用应该不多, 另外是应用单独配置的,
它应该不是放到org.deepin.dde.am这个配置文件中, 这个是dde-am工具使用的,而启动应用的是app-manager的服务,

2024-05-22 05:15 UTC, 18202781743 commented on src/dbus/applicationservice.cpp
> +#include "config.h"
?

2024-05-22 05:17 UTC, zccrs commented on misc/dsg/configs/dde-application-manager/org.deepin.dde.am.json
> +    "appsExtraEnvironments": {
+1

2024-05-22 05:18 UTC, zccrs commented on src/dbus/CMakeLists.txt
> +    Dtk6::Core
debian 目录里是不是也要加上编译依赖

2024-05-22 05:19 UTC, zccrs requested changes

2024-05-22 05:19 UTC, zccrs commented on src/dbus/applicationservice.cpp
> +            envs.append(ee.toString());
这是添加新的环境变量？黑名单如何实现呢？

2024-05-22 06:59 UTC, kegechen commented on src/dbus/CMakeLists.txt
> +    Dtk6::Core
本来就有这个依赖

2024-05-22 07:00 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            envs.append(ee.toString());
```
dde-dconfig set -a org.deepin.dde.application-manager -r org.deepin.dde.am -k appsExtraEnvironments -v  "{ \"FoxitReader\" : \"QT_QPA_PLATFORM=xcb\" }"

```

2024-05-22 07:01 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            envs.append(ee.toString());
黑名单功能太针对， 这个可以覆盖这种场景

2024-05-22 07:17 UTC, kegechen commented on misc/dsg/configs/dde-application-manager/org.deepin.dde.am.json
> +    "appsExtraEnvironments": {
ok， 以 `appid` 为 `subpath`， 不复用 `am.json`  这个 `meta` 文件

2024-05-22 08:05 UTC, zccrs commented on src/dbus/applicationservice.cpp
> +            envs.append(ee.toString());
黑名单和白名单都要加。如果是 "QT_QPA_PLATFORM=xcb"，在wayland环境下怎么办？这里的需求应该是 unset 这个环境变量，而不是为这个环境变量改一个值。

2024-05-22 09:20 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            envs.append(ee.toString());
白名单可以用这个接口，黑名单由于 `AM` 使用的是 `systemd.StartTransientUnit` 接口将额外属性设置进去的，暂时没有好的办法来清空环境变量，目前可能有的两个方案是：
- 清空环境变量，把**空**当做**清空**， `"QT_QPA_PLATFORM="`
- 启动前记录就得环境变量 `old` 然后清空 `systemd.UnsetEnvironment(QT_QPA_PLATFORM)`, 启动后 `systemd.SetEnvironment(QT_QPA_PLATFORM=old)`

方案1 对于那种判断是否设置环境变量的无效
方案2 如果启动应用过程中启动其他应用可能会出现环境变量丢失的问题 

@black-desk 有其他方式吗

2024-05-22 10:04 UTC, black-desk commented
有个属性叫 UnsetEnvironment systemd的那个起临时服务的 StartTransientUnit 接口吃这个属性。 @zccrs @kegechen

2024-05-24 06:52 UTC, zccrs requested changes

2024-05-24 06:52 UTC, zccrs commented on misc/dsg/configs/dde-application-manager/org.deepin.dde.application-manager.json
> +      "value": "",
应该是一个 `{}` 或者是 `[]`？

2024-05-24 06:52 UTC, zccrs commented on src/launchoptions.cpp
> +    auto str = m_val.toString();
为什么是 string, 多个环境变量时怎么办？

2024-05-24 06:52 UTC, zccrs commented on src/launchoptions.h
> +    [[nodiscard]] static const QString &key() noexcept
应该是 QStringList ？

2024-05-24 08:43 UTC, kegechen commented on src/launchoptions.cpp
> +    auto str = m_val.toString();
用 `;` 分开

2024-05-24 08:43 UTC, kegechen commented on misc/dsg/configs/dde-application-manager/org.deepin.dde.application-manager.json
> +      "value": "",
用 ; 分开

2024-05-24 08:45 UTC, kegechen commented on src/launchoptions.h
> +    [[nodiscard]] static const QString &key() noexcept
这里对应的是 "unsetEnv" 是map的key， value是要清除的环境变量名称

2024-05-27 02:38 UTC, ComixHe requested changes

2024-05-27 02:38 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
unsetEnv是仅供内部使用的option吗? 如果是的话可以看一下这里 https://github.com/linuxdeepin/dde-application-manager/blob/2dcc4a12e6521afaa408cf3fb17ed5bfb6b1a348/src/dbus/applicationservice.cpp#L248

2024-05-27 03:00 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
放到option里面也可以接受把，用户指定要清理某些环境变量（比如禁用屏幕缩放时就可以用这个，比以前用QT_SCALE_FACOTR=1 要友好）

2024-05-27 05:08 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
我的意思是如果这个仅限内部使用，可以把 `unsetEnv` 写成 `_unsetEnv`，然后和`_hooks`一样用 `optionsMap.remove` 防止可能从调用方传入的 `_unsetEnv`

2024-05-27 05:46 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
算  public property 允许从调用方传入也没啥问题吧

2024-05-27 07:22 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
如果这个是允许调用方传入的，那就改一下 api/org.desktopspec.ApplicationManager1.Application.xml 里的文档吧

2024-05-27 07:26 UTC, ComixHe commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
不过如果允许调用方传入，这里不能直接append吧？这里和上面应该需要先把用户传入的字符串和从配置来的字符串按';'分隔，然后按照优先级生成个列表出来，在把列表拼成字符串

2024-05-28 02:52 UTC, kegechen commented on src/dbus/applicationservice.cpp
> +            runtimeOptions.insert("unsetEnv", envsBlacklist);
unset传入的列表没有优先级， 只是不能重复，不过这个是否重复需要调用者自行保证。AM不做检查

2024-05-29 02:55 UTC, zccrs requested changes

2024-05-29 02:55 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +                          this application without them, eg. '[LANG=en_US;PATH=xxx:yyy;]'
`'["LANG=en_US", "PATH=xxx:yyy"]'`

2024-05-29 02:55 UTC, zccrs commented on src/launchoptions.cpp
> +    auto content = list.join(';');
在join之前要先把 `;` 转义一下。

2024-05-29 02:55 UTC, zccrs commented on src/launchoptions.cpp
> +    auto content = list.join(';');
同上

2024-05-29 02:55 UTC, zccrs commented on src/launchoptions.h
> +    [[nodiscard]] const QString &type() const noexcept override
这里的type是指谁的type，应该是 QStringList 吗？

2024-05-29 09:08 UTC, kegechen commented on src/launchoptions.h
> +    [[nodiscard]] const QString &type() const noexcept override
原设计定以了三种 `type`
```cpp
constexpr auto systemdOption = u8"systemd";
constexpr auto splitOption = u8"split";
constexpr auto AppExecOption = u8"appExec";
```

2024-05-29 09:29 UTC, kegechen commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +                          this application without them, eg. '[LANG=en_US;PATH=xxx:yyy;]'
xml 中 双引号中在用双引号会解析错误。。用  `&quot;` 也有点怪，直接不带引号把

2024-05-29 09:31 UTC, kegechen commented on src/launchoptions.cpp
> +    auto content = list.join(';');
转义空格？ `replace(" ", "\ ")`

2024-05-31 03:33 UTC, kegechen commented on src/launchoptions.cpp
> +    auto content = list.join(';');
统一使用  `:`  作为分隔符，这种文件（目录）名是不合法的

2024-06-04 08:40 UTC, zccrs commented on src/launchoptions.cpp
> +    auto content = list.join(';');
并没有这样的规定，可能只是我们的文件管理器里不让用 `:`

2024-06-05 08:34 UTC, kegechen commented on src/launchoptions.cpp
> +    auto content = list.join(';');
这个 `:`环境变量中分隔符比较常用的。

2024-06-06 09:42 UTC, kegechen commented on src/launchoptions.cpp
> +    auto content = list.join(';');
改了。
其实只有额外环境变量需要处理，如果环境变量 `value` 中有 `:` 会替换成 `\:`, 处理时会检测这个 `\:` 不作为分隔符
黑名单因为只需要 `key` 所以不存在  `:`

2024-06-06 10:09 UTC, zccrs submitted a review, later dismissed

2024-06-06 10:09 UTC, zccrs commented on apps/app-launch-helper/src/variantvalue.cpp
> +        if (line.back() == '\\') {  // '\:'
这是错误的实现。正常写一个“转义”和“反转义”的函数！！chatgpt轻轻松松都能写出来。

2024-06-07 00:58 UTC, kegechen commented on apps/app-launch-helper/src/variantvalue.cpp
> +        if (line.back() == '\\') {  // '\:'
`am` 通过命令行参数传递给 `am-launch-helper --Environment="E1=e1\\:e2\\:e3:E2=xx\\:yy\\:zz"`

`am` 已经加了 `转义` 方法

`am-launch-helper`  没有引入 `Qt ` 用 `std::getline(str, ':')` 处理 "E1=e1\\:e2\\:e3:E2=xx\\:yy\\:zz" 所以不能直接反转义，需要边读取边处理。

以下结果来自chatgpt :sob: 
```cpp
std::string escape_colon(const std::string& input_string) {
    /**
     * 对字符串中的 ':' 进行转义处理
     */
    std::string escaped_string;
    for (char c : input_string) {
        if (c == ':') {
            escaped_string += "\\:"; // 转义 ':' 为 '\\:'
        } else {
            escaped_string += c;
        }
    }
    return escaped_string;
}

std::string unescape_colon(const std::string& input_string) {
    /**
     * 对字符串中的转义过的 ':' 进行反转义处理
     */
    std::string unescaped_string;
    for (size_t i = 0; i < input_string.length(); ++i) {
        if (input_string[i] == '\\' && i < input_string.length() - 1 && input_string[i + 1] == ':') {
            // 如果遇到转义字符 '\\:', 则跳过 '\\', 只取 ':'
            unescaped_string += ':';
            ++i;
        } else {
            unescaped_string += input_string[i];
        }
    }
    return unescaped_string;
}

```

2024-06-07 06:23 UTC, kegechen commented
多个环境变量参数通过多次传递来防止出现转义

`--ExecSearchPath=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin`

```
--ExecSearchPath=/usr/local/bin
--ExecSearchPath=/usr/bin
--ExecSearchPath=/bin
--ExecSearchPath=/usr/local/games
--ExecSearchPath=/usr/games
--ExecSearchPath=/sbin
--ExecSearchPath=/usr/sbin
```

2024-06-07 06:27 UTC, zccrs commented
/+1

2024-06-07 06:28 UTC, ComixHe approved these changes

2024-06-13 03:32 UTC, merged