feat: add startupwmclass prop export
linuxdeepin/dde-application-manager pull request #229
Opened 2024-09-03 11:12 UTC by tsic404

log: as title

2024-09-03 11:48 UTC, BLumia submitted a review, later dismissed
dde-shell 依赖此接口的时候记得在 debian/control 中添加版本检查

2024-09-03 18:14 UTC, ComixHe requested changes

2024-09-03 18:14 UTC, ComixHe commented on src/desktopfilegenerator.cpp
> +    if (key == "StartupWMClass") {
这个函数之前实现的有点问题，而且这里其实不用写，外面会处理StartupWMClass的，这里面应该只处理以UTF-8编码可能和locale有关的字段。

2024-09-05 05:26 UTC, ComixHe approved these changes

2024-09-10 01:55 UTC, merged