fix GIO_LAUNCHED_DESKTOP_FILE_PID
linuxdeepin/dde-application-manager pull request #30
Opened 2023-04-20 02:55 UTC by black-desk

- build: remove dtkwidget
- fix: set GIO_LAUNCHED_DESKTOP_FILE_PID

2023-04-22 09:18 UTC, zccrs requested changes

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +        envs.insert("GIO_LAUNCHED_DESKTOP_FILE_PID", QString::number(getpid()).toUtf8().constData());
用 QByteArray

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +    signal(SIGCHLD,sig_child);
sig_child 前的空格

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +        char const* args[process.arguments().length()+1];
+ 号两边的空格

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +        args[process.arguments().length()]=0;
同上

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +        std::transform(process.arguments().constBegin(), process.arguments().constEnd(), args, [](const QString& str){
arguments() 是个临时变量，不确定是否有问题

2023-04-22 09:18 UTC, zccrs commented on src/modules/startmanager/startmanager.cpp
> +        execvpe(process.program().toUtf8().constData(), (char**)args, (char**)envs);
toLocal8Bit()

2023-04-22 09:19 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        char const* args[process.arguments().length()+1];
> `*` 号两边的空格

2023-04-22 09:23 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        envs.insert("GIO_LAUNCHED_DESKTOP_FILE_PID", QString::number(getpid()).toUtf8().constData());
> 用 QByteArray

done

2023-04-22 09:24 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        char const* args[process.arguments().length()+1];
done

2023-04-22 09:24 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        args[process.arguments().length()]=0;
done

2023-04-22 09:25 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        std::transform(process.arguments().constBegin(), process.arguments().constEnd(), args, [](const QString& str){
done

2023-04-22 09:25 UTC, black-desk commented on src/modules/startmanager/startmanager.cpp
> +        execvpe(process.program().toUtf8().constData(), (char**)args, (char**)envs);
done

2023-04-22 09:29 UTC, zccrs approved these changes

2023-04-22 09:29 UTC, merged

2023-04-23 01:41 UTC, black-desk commented
@zccrs 以后我的提交还是就 不要squash了 rebase就可以了 或者@我我自己推到master去, 带signoff的commit squash了太丑了

2023-04-23 01:42 UTC, zccrs commented
> @zccrs 以后我的提交还是就 不要squash了 rebase就可以了 或者@我我自己推到master去, 带signoff的commit squash了太丑了

OK，点错了，我们可以默认禁用 squash