fix: 退出没有图标的应用AM崩溃
linuxdeepin/dde-application-manager pull request #34
Opened 2023-04-22 04:42 UTC by dengbo11

在处理窗口改变时需要判断当前任务栏驻留的应用是否是有效的, 有效才去更新

Log: 修复没有图标的应用退出时AM奔溃退出的问题
Influence: 任务栏应用图标正常显示

2023-04-22 10:48 UTC, BLumia approved these changes

2023-04-23 08:28 UTC, black-desk commented on src/lib/xcbutils.cpp
> +            for (int i = 0; i < (2 + area) * 4; ++i, ++data) {
没改变逻辑的话 就先别动这个

2023-04-23 08:29 UTC, dengbo11 commented
@black-desk

2023-04-23 08:29 UTC, black-desk commented on src/lib/xcbutils.cpp
> +            if (iter.width > 0 && iter.width > wmIconIt.width) {
既然是size最大不如用两个乘起来的比较 这个宽和高一定是完全一样的么

2023-04-23 08:31 UTC, black-desk commented on src/lib/xcbutils.cpp
> +            std::vector<long> ret;
在这里说明一下为什么换类型

2023-04-23 08:32 UTC, black-desk commented on src/lib/xcbutils.h
> +    WMIcon getWMIcon(XWindow xid);
原来是return一个列表让外面选 你现在改成只return一个了?

2023-04-23 08:32 UTC, black-desk commented on src/modules/dock/windowinfox.cpp
> +    QImage img = QImage((uchar *)icon.data.data(), icon.width, icon.width, QImage::Format_ARGB32);
之前的那个图标看起来不对的问题解决了么

2023-04-23 08:33 UTC, black-desk requested changes
逐条回复一下吧

2023-04-23 08:34 UTC, black-desk commented
@zsien 一起看看 我头有点晕(

2023-04-23 08:39 UTC, dengbo11 commented on src/lib/xcbutils.cpp
> +            std::vector<long> ret;
传入的类型是data是uint32类型的, 如果使用unsigned char 会造成数据截断,导致图片数据错误,进而导致显示异常.

2023-04-23 08:40 UTC, black-desk commented on src/lib/xcbutils.cpp
> +            std::vector<long> ret;
那是不是应该用uint32_t

2023-04-23 08:40 UTC, dengbo11 commented on src/lib/xcbutils.h
> +    WMIcon getWMIcon(XWindow xid);
这个是参考dde-daemon原来的逻辑改的,因为后面要进行图片缩放, 一般选择最大的就行

2023-04-23 08:40 UTC, dengbo11 commented on src/modules/dock/windowinfox.cpp
> +    QImage img = QImage((uchar *)icon.data.data(), icon.width, icon.width, QImage::Format_ARGB32);
done

2023-04-23 08:41 UTC, black-desk commented on src/lib/xcbutils.h
> +    WMIcon getWMIcon(XWindow xid);
其他地方没人用么, 没人用就算了 你把dde-daemon对应代码的链接贴过来一下就行

2023-04-23 08:59 UTC, zsien requested changes

2023-04-23 08:59 UTC, zsien commented on src/lib/xcbutils.cpp
> +            const int oldSize = wmIconIt.width * iter.height;
用「old」不太合适

2023-04-23 08:59 UTC, zsien commented on src/lib/xcbutils.cpp
> +                wmIconIt.data = iter.data;
可以直接 wmIconIt = iter

2023-04-23 09:38 UTC, zsien requested changes

2023-04-23 09:38 UTC, zsien commented on src/lib/xcbutils.cpp
> +            const auto size = (2 + it.width * it.height) * 4;
这里的 * 4 是不需要的吧

2023-04-23 09:53 UTC, zsien approved these changes

2023-04-23 09:55 UTC, merged