Remove almost all files in this project.
linuxdeepin/dde-application-manager pull request #56
Opened 2023-05-26 01:49 UTC by black-desk

This is a prepare PR for later refactor from ground.

2023-05-26 02:13 UTC, black-desk commented
@zccrs @BLumia @xzl01 @tsic404

2023-05-26 03:28 UTC, xzl01 commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +        <method name="Icon">
所以AM还是要给应用提供icon获取方式吗？

2023-05-26 03:28 UTC, xzl01 commented on api/dbus/org.desktopspec.JobManager1.Job.xml
> +    <interface name="org.desktopspec.JobManager1.Job">
如果要实现job管理 是否需要dtk做一套类似机制？

2023-05-26 03:29 UTC, black-desk commented on api/dbus/org.desktopspec.JobManager1.Job.xml
> +    <interface name="org.desktopspec.JobManager1.Job">
我觉得可能在am里面先做 用得差不多了再往dtk复制代码 会比较合适

2023-05-26 03:37 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +        <method name="Icon">
看这个方法的说明。
为了防止通过dbus接口调用am的程序/桌面组件无法正常获取到icon。有必要提供这个接口。
这是出于
1. AM要考虑调用者在其他容器中的情况。
2. AM的职责之一是对desktop文件的封装。

2023-05-26 05:07 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +</node>
文末回车

2023-05-26 05:07 UTC, black-desk commented on api/dbus/org.desktopspec.JobManager1.xml
> +</node>
文末回车

2023-05-26 05:16 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +            <arg type="h" name="desktop_file_fd" direction="out" />
因为要考虑：

1. 调用者在容器中，或者被限制了访问某个目录；

   所以根本拿不到这个文件。

3. 给fd可以保证拿到fd的人对这个desktop文件是只读的。
   
   NOTE: fcntl(2)的F_SETFL并不能够改变fd的读写权限。

2023-05-26 05:17 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +            <arg type="h" name="pidfd" direction="in" />
因为pidns可能不一样。pidfd就是用来做这个事情的。

2023-05-26 05:17 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Instance.xml
> +        <property name="SystemdPath" type="o" access="read">
是

2023-05-26 05:20 UTC, black-desk commented
https://github.com/linuxdeepin/dde-application-manager/pull/56#discussion_r1206209420

这个Icon方法算是对xdg的spec, 在跨容器情况下的补丁。只考虑XDG范畴的。

DCI的标准定下来以后专门加一个DCI的方法。

2023-05-26 05:22 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +        <method name="Icon">
这个Icon方法算是对xdg的spec, 在跨容器情况下的补丁。只考虑XDG范畴的。

DCI的标准定下来以后专门加一个DCI的方法。

非容器内应用可以不使用。对使用不使用不做建议。

2023-05-28 04:58 UTC, xzl01 commented
建议这次提交把.gitignore加上

2023-05-29 02:11 UTC, black-desk commented
> 建议这次提交把.gitignore加上

我倾向于等真的开始写代码了再提。

2023-05-29 02:30 UTC, xzl01 approved these changes
+1

2023-05-29 09:53 UTC, BLumia approved these changes

2023-05-30 07:20 UTC, zccrs requested changes

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +            <arg type="s" name="group" direction="in" />
为什么允许指定group呢，标准中也是可以随意定group的吗

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +                       Check https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#desktop-file-id
这里的id不应该显式的指明跟 freedesktop 有啥关系，要指也应该是指到 https://github.com/linuxdeepin/deepin-specifications 里

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +        <method name="List">
这个为什么不作为一个属性呢

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +        </method>
最好再给出一个 String 的方法，直接返回这个 pid 对应的程序的 ID 字符串表示的内容。需要获取一个程序 id 字符串的场景是最多的，从三个DBus调用简化到一个调用是值得的。

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +    </interface>
缺少一个从字符串的ID获取一个DBus Application interface的方式

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.JobManager1.Job.xml
> +        <method name="Cancel">
实现的时候到底哪个阶段可以被取消？

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.JobManager1.Job.xml
> +        <method name="Cancel">
另外没有Stop的方式吗？

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.JobManager1.xml
> +                       `result` is the result this job produce if it success."
result由谁提供，可能是个什么样的数据？

2023-05-30 07:20 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +</node>
没有直接通过程序的字符串 ID 启动程序的方法吗？

2023-05-30 07:22 UTC, zccrs requested changes

2023-05-30 07:22 UTC, zccrs commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +</node>
以及打开一个url的方法

2023-05-30 08:25 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +            <arg type="s" name="id" direction="in" />
因为不同的action可能会用到不同的icon。我怕不让传id的话，所有的action就都只能显示成主字段里面的那个icon了。

2023-05-30 08:27 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> +            <arg type="s" name="group" direction="in" />
这个group的名字起得不好，应该说是action。

就右键菜单里的那个项。

2023-05-30 08:28 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +        <method name="List">
怕发属性变更信号的时候代价太大了。

2023-06-01 02:29 UTC, black-desk commented on api/dbus/org.desktopspec.JobManager1.Job.xml
> +        <method name="Cancel">
这个接口是QFuture的封装，可能绝大多数没有经过设计的job都是不能取消的。

2023-07-05 05:37 UTC, black-desk commented on api/dbus/org.desktopspec.ApplicationManager1.xml
> +</node>
经过讨论应该放在xdg-protal中实现.

2023-07-05 05:38 UTC, black-desk commented
@ComixHe @l631197874 看看这个.

2023-07-05 06:47 UTC, l631197874 approved these changes

2023-07-05 06:47 UTC, l631197874 approved these changes

2023-07-05 06:48 UTC, l631197874 approved these changes

2023-07-05 08:13 UTC, BLumia approved these changes

2023-07-06 02:01 UTC, l631197874 approved these changes

2023-07-06 02:02 UTC, l631197874 approved these changes

2023-07-06 02:02 UTC, l631197874 approved these changes

2023-07-06 02:03 UTC, l631197874 approved these changes

2023-07-06 02:05 UTC, merged