fix: 卸载第三方应用后任务栏依然显示应用
linuxdeepin/dde-application-manager pull request #65
Opened 2023-06-20 07:40 UTC by dengbo11

在通过laucher卸载应用后, 调用dock接口取消应用的驻留

Log: 修复卸载第三方应用后任务栏依然显示应用的问题
Influence: 任务栏应用正常显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4630

2023-06-20 07:41 UTC, dengbo11 commented
/integrate

2023-06-20 07:41 UTC, black-desk commented
应用商店里面的应用是怎么处理的？

2023-06-20 08:48 UTC, tsic404 commented
问题应该不在这，应该是 https://github.com/linuxdeepin/dde-application-manager/blob/master/src/modules/dock/dock.cpp#L1411-L1419 出了问题。

这样采用launcher拆卸时发送信号的操作，会导致从其他入口，比如终端拆卸时。没有触发此处代码，导致依旧无法移除对应的Entry。

2023-06-25 03:11 UTC, dengbo11 commented
@black-desk @tsic404

2023-06-25 03:29 UTC, black-desk commented
commit 标题中不要描述自己修了什么bug 而是应该描述自己做了什么更改。

比如说这次应该是 “fix(launcher): 修正onCheckDesktopFile的行为” 之类的吧？

2023-06-25 03:30 UTC, black-desk requested changes
commit message

2023-06-25 05:25 UTC, black-desk approved these changes

2023-06-25 05:29 UTC, dengbo11 commented
/integrate

2023-06-25 05:29 UTC, merged

2023-06-25 06:26 UTC, dengbo11 commented
/integrate