chore: init project structure
linuxdeepin/dde-application-manager pull request #70
Opened 2023-07-06 10:34 UTC by ComixHe

Log: 初始化项目结构

2023-07-06 15:31 UTC, black-desk commented on CMakeLists.txt
> +    VERSION 0.0.1
严格按照semver来的话 第一个版本应该是0.1.0

最后一位版本号是用来做前向兼容的bug修复的。

2023-07-07 01:38 UTC, ComixHe commented on CMakeLists.txt
> +    VERSION 0.0.1
done

2023-07-07 01:45 UTC, black-desk commented on CMakeLists.txt
> +
空行

2023-07-07 02:05 UTC, black-desk commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
全去了.

pthread应该用FindThreads去找.

2023-07-07 02:07 UTC, black-desk commented on CMakeLists.txt
> +if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
默认的install prefix就应该是local.

你的cmakelist里面的install首先应该考虑对从源码编译安装的人负责.

而从源码编译安装的人不会希望装下去的东西和包管理器管的部分冲突.

2023-07-07 02:08 UTC, black-desk commented on LICENSE
@BLumia 这个LICENSE文件有必要把LGPL的和GPL的都写进来么

2023-07-07 02:09 UTC, black-desk requested changes
如上

2023-07-07 02:30 UTC, BLumia commented on LICENSE
只提供这个 LICENSE 而不提供 LICENSES 目录的话是有的，LGPL 的需要带 GPL。这个本身也没什么问题。

2023-07-07 02:31 UTC, black-desk commented on LICENSE
fine

2023-07-07 02:34 UTC, BLumia commented on .reuse/dep5
> +License: CC0-1.0
clang-format 配置文件本身支持注释，所以其实可以在 clang-format 文件的最上面写 spdx license indicator，就不需要改这个文件了。

2023-07-07 03:26 UTC, ComixHe commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
所有的CXX_FLAGS吗？

2023-07-07 07:44 UTC, merged